import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About-Us",
  description: "Generated by create next app",
};

export default function Login({ children }: { children: React.ReactNode }) {
  return <section>{children}</section>;
}
