import type { Metadata } from "next";
import { getTotalMeals } from "@/services/dashboard/manager.messTotalMeals";
import { getTotalMealExpense } from "@/services/dashboard/manager.messTotalMealExpense";
import DashboardLayout from "@/components/dashboard/dashboardLayout";
import { GetUserById, GetMessByUserId } from "@/services/getUserById";
import { usersMeals } from "@/services/users.meals";
import { userMoneySubmit } from "@/services/user.moneySubmit";
import { getUtilityCosts } from "@/services/dashboard/manager.getUtilityCost";

export const metadata: Metadata = {
  title: "Manager Dashboard",
  description: "Generated by create next app",
};

export default async function Login({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ data: string }>;
}) {
  const { data: userID } = await params;

  const totalMeals = await getTotalMeals();
  const totalMealExpense = await getTotalMealExpense();
  const perHeadMeal =
    totalMeals > 0 ? Math.round(totalMealExpense / totalMeals) : 0;

  const user = await GetUserById(userID);
  const userMeals = await usersMeals(userID);
  const userSubmitMoney = await userMoneySubmit(userID);
  const userTotalCost =
    userMeals.totalMeals > 0
      ? Math.round(userMeals.totalMeals * perHeadMeal)
      : 0;
  const userInTotalCost = userSubmitMoney.totalAmount - userTotalCost;

  const messID = await GetMessByUserId(userID);
  const utilityCost = await getUtilityCosts(messID);

  return (
    <>
      <DashboardLayout
        role="manager"
        userName={user.name}
        userEmail={user.email}
        userNID={user.nid}
        userPhone={user.phone}
        totalMeals={totalMeals}
        totalMealExpense={totalMealExpense}
        perHeadMeal={perHeadMeal}
        userMeals={userMeals.totalMeals}
        userSubmitMoney={userSubmitMoney.totalAmount}
        userTotalCost={userTotalCost}
        userInTotalCost={userInTotalCost}
        utilityCost={utilityCost}
        messID={messID}
      >
        {children}
      </DashboardLayout>
    </>
  );
}
