import type { Metadata } from "next";
import { getTotalMeals } from "@/services/dashboard/manager.messTotalMeals";
import { getTotalMealExpense } from "@/services/dashboard/manager.messTotalMealExpense";
import DashboardLayout from "@/components/dashboard/dashboardLayout";
import { GetUserById } from "@/services/getUserById";

export const metadata: Metadata = {
  title: "Manager Dashboard",
  description: "Generated by create next app",
};

export default async function Login({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ data: string }>;
}) {
  const { data: userID } = await params;

  const totalMeals = await getTotalMeals();
  const totalMealExpense = await getTotalMealExpense();
  const perHeadMeal =
    totalMeals > 0 ? Math.round(totalMealExpense / totalMeals) : 0;
  const user = await GetUserById(userID);

  return (
    <>
      <DashboardLayout
        role="manager"
        userName={user.name}
        totalMeals={totalMeals}
        totalMealExpense={totalMealExpense}
        perHeadMeal={perHeadMeal}
      >
        {children}
      </DashboardLayout>
    </>
  );
}
