import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function Register({ children }: { children: React.ReactNode }) {
  return <section>{children}</section>;
}
